- src/components/Header.astro
- src/components/navigation/NavItem.astro
Desktop part of https://github.com/gathering/tgno-frontend/issues/95
Should be enough to unblock any issues that either requires multiple levels of navigation or child-items without a top level page (we see some cases of this in current project due to content production delays). On mobile we still have a bit of room to go on before we are filled up
Introduces NavItem that essentially have four possible states (when being hovered). When not hovered it gets highlighted as active if itself or any child item matches current path (exactly)
Non-clickable top item, with children
Non-clickable top item, no children (🤔)
Clickable top item, with children
Clickable top item, no children
> feat: add desktop sub navigation support

- src/components/Header.astro
- src/components/navigation/NavItem.astro
Closes: https://github.com/gathering/tgno-frontend/issues/95
Expands: https://github.com/gathering/tgno-frontend/pull/105
Previous iteration was nice, clean and purely CSS based. It did however have some limitations when it came to touch input, and how to use it in mobile (hamburger) navigation context.
This update should fix most of this allowing us to iterate on behaviour and styling as need develop
- On non-touch devices (ie. desktop) sub navigation expands on hover, leaving the "top item" actually clickable
- On non-mobile touch devices (ie. tablets) sub navigation expands on tap/click, and instead moves "top item" inside the dropdown
- On mobile we show hamburger menu layout with tablet interactions
Desktop, an item under "konkurranser" is the current page
Mobile hamburger menu …
> feat: mobile and touch friendly multi level navigation

- src/components/Header.astro
Nothing controversial, just making it work better on the smaller mobile screen sizes
> fix: avoid breaking date and location header on mobile

- src/components/Footer.astro
Removed duplicate "kontakt oss" link in footer section.
Should be replaced with new link to another source.
> Fix: duplicate

- src/components/navigation/NavItem.astro
As reported in: https://gathering.slack.com/archives/C07Q9QH2U2X/p1732621362953799
With fix in place navigation should work as expected in safari desktop.
> fix: querySelectorAll array in safari

- src/components/frontpage/InfoBox.astro
As reported on slack, this should avoid case of endlessly-high-frontpage-images in Safari desktop browsers
> fix: frontpage box scaling on safari

- src/components/Header.astro
- src/components/HeaderNavigation.astro
- src/components/navigation/NavItem.astro
- src/types/index.ts
- src/types/navigation.ts
Closes: https://github.com/gathering/tgno-frontend/issues/114
Still a couple of quirks to iron out, but should (🤞) fix issue goals. Logic is
- Show top navbar items from `md` and up, gradually showing more items as needed (hide rightmost item when out of space)
- Show hamburger for all sizes, always including all menu items
- Switch all navigation items from hover to click/tap/toggle on touch devices
- ...
Desktop with room for all top items
... with expanded hamburger
... with hovered nav item
Slightly smaller viewport with nav items hidden
Smallest (mobile) breakpoint with only hamburger menu
... with expanded hamburger
> feat: add combined hamburger and hover navigation

- public/tg25/tg25_horizontal_white.svg
- public/tg25/tg25_icon_white.svg
- public/tg25/tg25_square_white.svg
- src/components/Header.astro
Closes: https://github.com/gathering/tgno-frontend/issues/117
**Do not merge, only switched out of draft state to get review url**
In order to make logo details comfortable enough I had to increase header size a bit. Think slimmer header looks a bit nicer, but not end of the world.
Did not change favicon, as I'm not quite sure icon is very TG recognisable. Example
Ended up using the horisontal logo variant for all cases, since
- It doesn't require any more height than the square variant (and provides more relevant info/context)
- It bears way more profile/theme context than standalone symbol
> feat: add tg25 logo to header

- src/components/Header.astro
- src/components/NewsComp.astro
- src/components/Pagination.astro
- src/components/frontpage/NewsComp.astro
- src/pages/index.astro
- src/pages/news/index.astro
- src/types/articles.ts
- src/utils/articles.ts
Closes: https://github.com/gathering/tgno-frontend/issues/101
Adds pagination to news page and exposes it in the relevant places.
> feat: expose news page to users

- src/components/tickets/TicketBox.astro
- src/pages/tickets/index.astro
Added:
- Relative class to ticket component
- Sold out div with styling
Closes #127
> Feat: sold out tag, 1337 ticket

- Dockerfile
Trying to fix errors that have just started to show up
> chore: always use latest corepack version in docker image

- src/components/navigation/NavItem.astro
Closes: https://github.com/gathering/tgno-frontend/issues/133
Also changes name of top item to make it less of an echo from item itself, hopefully generic enough to work with any nav item.
> feat: always include duplicate top nav items

- src/components/practical/PracticalPage.astro
- src/layouts/Layout.astro
- src/pages/news/[slug].astro
- src/pages/practical/[...path].astro
- src/pages/tickets/index.astro
Part of: https://github.com/gathering/tgno-frontend/issues/134
Adds json-ld data to a few different page types to hopefully make them easier to parse and present to search engines (google)
> feat: add json-ld to various pages

- src/components/ContentContainer.astro
- src/components/frontpage/NewsComp.astro
- src/pages/news/[slug].astro
- src/types/articles.ts
- src/utils/articles.ts
Closes: https://github.com/gathering/tgno-frontend/issues/59
Adds some nice styling, and moves meta data after main article contents. I think this aligns with how we use bylines and publish date; important to have available (both for us, contributors and readers), but generally not supposed to be read.
Desktop
Mobile
Before
> feat: style article meta data

- src/pages/event/rules.astro
- src/pages/tickets/terms-and-conditions.astro
Requested via slack, should be self explanatory. Linking to main consent form page instead of pdf, since we expect different pdf per year
> fix: add missing consent form links

- src/types/articles.ts
- src/utils/articles.ts
Blocked by: https://github.com/gathering/tgno-backend/pull/42
Part of: https://github.com/gathering/tgno-backend/issues/31
Once backend changes have been merged this should remove frontend custom sorting and instead rely on API defaults (which was previously "wrong").
> fix: respect default backend article ordering

- src/pages/schedule/index.astro
When looking at a specific day of events there can/will be events that started the day before and overlap with a few hours. There are several ways to handles this (why we have different event styles, etc). For now we will just hide said events to make it easier to parse (even if it becomes slightly less informative/correct)
Option A - View it as "normal" (but note additional info on duration)
Option B - Show it in a more descrete variant (I think this is what we ideally want long term, if we can find a good design for it)
Option C - Don't show it at all
For now we went with option C. But events are available to frontend, so can be tweaked as needed without backend changes
> feat: filter out events that started outside range

- src/components/schedule/Event.astro
- src/utils/events.ts
With https://github.com/gathering/tgno-backend/pull/46/files#diff-6f6a60ed2af6e4824039d2489ce354836618088d2433ffcbde255b70da0104adR67 in place we should hopefully not need this anymore
(Diff is a bit confusing, but only sorting on line 37 was removed)
> chore: remove unused client side event sorting

- src/pages/schedule/index.astro
When looking at a specific date in calendar we only show events that start on that specific day. It was raised that we also have a couple of events starting right after midnight that it would probably be nice for users to see when looking at the day before.
For example this is what it looks like today
And this is what it would looks like if we also including the next few hours of the next day
> feat: show 2 hours into next day when filtering calendar

- src/pages/about/expo.astro
- src/pages/about/index.astro
- src/pages/about/sponsor.astro
Reported via slack. We could in theory also change to a smarter image component, but also that would probably have some challenges when it comes to optimising png images. So replacing image here and in the related tg.no article.
> fix: remove use of png images

- src/components/Header.astro
- src/types/info.ts
Closes: https://github.com/gathering/tgno-frontend/issues/176
Blocked by: https://github.com/gathering/tgno-backend/pull/47
Before we roll this out we should probably make sure info is in the loop and that the relevant pages are ready (marked as show in menu, and in the correct order)
> feat: populate practical nav item with backend pages

- tools/create-preview.py
Noticed a lot of review app namespaces being left in k8s after review app is deleted. Argo CD discussion thread seems to indicate that this change should allow Argo CD to track namespace after creation and include it in cleanup tasks.
> feat: annotate review app namespaces to allow cleanup

- src/components/floating-nav/FloatingNav.astro
- src/components/icons/ChevronDownSymbol.astro
- src/components/icons/FilterSymbol.astro
- src/components/schedule/ActiveFilterNav.astro
- src/components/schedule/Event.astro
- src/components/schedule/FullFilterNav.astro
- src/pages/schedule/index.astro
- src/types/events.ts
- src/utils/events.ts
First step of getting redesigned schedule in place. This first step is getting an explicit filtering menu in place, that is both available at top of page and sticky.
Also added experimental "highlighted event" functionality, not yet exposed on any actual buttons or links. The idea is that it will allow us to get SEO for individual events (the highlighted one), which is what google prefers over a list of events, but probably needs to be exposed in a smart way.
Ex. https://www.tg.no/schedule?event=3
Standard view
Top filtering menu
Floating filtering menu
Example of expanded view, note how only location is now shown
Highlighted event
> feat(schedule): sticky filtering menu

- src/types/events.ts
- src/utils/events.ts
Add info and konsert as category menu choices, as they seemed useful when looking at currently published events.
> chore(schedule): better categories, and fixed types

- src/components/icons/LiveSymbol.astro
- src/components/schedule/ActiveFilterNav.astro
- src/components/schedule/DayHeader.astro
- src/components/schedule/Event.astro
- src/components/schedule/FullFilterNav.astro
- src/types/events.ts
- src/utils/events.ts
Closes: https://github.com/gathering/tgno-frontend/issues/192
Will create a few follow up issues for minor details left out of first iteration. Main prio is to get changes out as soon as possible so that we unblock others from iterating on them during easter.
Ended events, followed by a live, and and expanded one
Colors used on top filtering menu (depends on category/location selected)
Example of colors in use on sticky menu
> feat(schedule): apply main parts of calendar redesign

- src/components/frontpage/DefaultHero.astro
- src/components/frontpage/Hero.astro
- src/components/frontpage/PracticalPageHero.astro
- src/components/practical/PracticalPage.astro
- src/pages/index.astro
- src/pages/practical/[...path].astro
- src/types/info.ts
Part of: https://github.com/gathering/tgno-frontend/issues/207
Blocked by: https://github.com/gathering/tgno-backend/pull/51
Page with image (always slim)
Front desktop
Front mobile
> feat(practical): frontpage teaser and related tweaks

- src/components/frontpage/NewsPageHero.astro
Part of: https://github.com/gathering/tgno-frontend/issues/207
Does nothing right now, but first part of supporting output from https://github.com/gathering/tgno-backend/pull/52 to dynamically control header section (and potentially also more parts of frontpage)
> feat(frontpage): create news page hero

- src/components/icons/CancelSymbol.astro
- src/components/schedule/Event.astro
- src/components/schedule/Schedule.astro
Ref ongoing calendar cleanups, this allows us to signal cancelled events in a similar way to how we do notices
If in the future
If in the past
> feat(schedule): add support for cancelled events
