gathering/tgno-frontend

src/components/sections/TicketsComp.astro, src/pages/tickets/index.astro
Requested and formulated based on https://gathering.slack.com/archives/CG3MSB329/p1730796455113229?thread_ts=1730794015.236949&cid=CG3MSB329
=> fix: update ticket text to reflect that queue is live

src/components/Footer.astro, src/pages/event/construction-rules.astro, src/pages/event/rules.astro, src/pages/tickets/terms-and-conditions.astro
Part of: https://github.com/gathering/tgno-frontend/issues/43
Part of: https://github.com/gathering/tgno-frontend/issues/91
Text should now be "correct", some questions still apply, but good enough for a first version. Ticket should remain open so that navigation and other improves could be done before it is done.
=> feat: ticket sale terms and conditions page

src/pages/competitions/creative.astro
Requested by Kreativia via slack
=> chore: adjust ai graphics text

src/components/Footer.astro, src/components/icons/BrandTiktok.astro
Closes: https://github.com/gathering/tgno-frontend/issues/93
=> feat: tiktok in footer

src/pages/contact.astro
Closes: https://github.com/gathering/tgno-frontend/issues/103
=> feat: add direct press contact information

src/components/Header.astro, src/components/Sponsors.astro
- set horizontal padding on navigation to px-5, staying consistent with the rest of the layout
- adjusted responsive styling at sponsor banner
=> fix: consistent spacing

src/pages/event/rules.astro
=> chore: updated ticket resale rules

src/pages/tickets/index.astro
=> feat: Add EXPOpass ticket info

package.json, pnpm-lock.yaml, src/components/frontpage/Hero.astro
Closes: https://github.com/gathering/tgno-frontend/issues/129
Note: YouTube seems a bit iffy when trying to autoplay with sound (we know browsers will actively try to block this in many cases) so always starting video in muted mode.
=> feat: add TG25 teaser to frontpage hero

src/pages/index.astro
Ønsket tekstendring, [tg.no](http://tg.no/) - forsiden:
Endre fra `BLI MED I NORGES STØRSTE PÅSKEHYTTE`
Endre til `FEM UFORGLEMMELIGE DAGER I NORGES FETESTE PÅSKEHYTTE!`
=> fix: change index title

src/components/competitions/Pill.astro, src/pages/competitions/esport.astro, src/pages/index.astro
Ref various threads on slack
* adds FTP button
* adds reference to Valorant tournament status
=> feat: misc info tweaks

src/components/tickets/TicketBox.astro, src/pages/tickets/index.astro
=> feat: Add more tickets

src/components/competitions/Pill.astro, src/pages/competitions/creative.astro
=> chore: update creativia competition information

src/components/Header.astro, src/components/icons/ArrowSymbol.astro, src/components/icons/CalendardSymbol.astro, src/components/icons/ClockSymbol.astro, src/components/icons/CloseSymbol.astro, src/components/icons/ExternalLinkSymbol.astro, src/components/icons/FilterCloseSymbol.astro, src/components/schedule/DayHeader.astro, src/components/schedule/Event.astro, src/pages/index.astro, src/pages/schedule/index.astro, src/types/events.ts, src/types/index.ts, src/utils/events.ts, src/utils/index.ts, src/utils/info.ts
Closes: https://github.com/gathering/tgno-frontend/issues/158
Do not merge, still work in progress, but out of draft to get review app.
Personal todo:
https://github.com/user-attachments/assets/47f3db2b-3a28-452c-ae6a-bc2273f6b90e
=> [WIP] feat: initial schedule version

src/components/competitions/SportsBox.astro, src/pages/competitions/esport.astro
Adds possibility to set urlText on SportsBox component, and showcases this on the esport page to add competition URLs.
=> feat: SportsBox urlText

src/pages/competitions/creative.astro
Closes: https://github.com/gathering/tgno-frontend/issues/184
Also reorders boxes a little bit to avoid ugly gaps when resizing (and move TG:Hack to a bit more prominent location)
=> feat: add creative minecraft compo

src/components/tickets/QueueGuideBox.astro, src/components/tickets/ReservationGuideBox.astro, src/components/tickets/TicketBox.astro, src/pages/tickets/index.astro
Closes: https://github.com/gathering/tgno-frontend/issues/186
~(Placeholder content, do not merge)~ Do not merge until https://www.tg.no/news/plassreservasjon-%C3%A5pner-26-mars has been published
=> feat: add reservation info to tickets page

src/pages/contact.astro
=> chore: updated contact info

src/pages/schedule/index.astro
Closes: https://github.com/gathering/tgno-frontend/issues/166
Not requested yet, but feels about time to remove it. Merging once I hear back from event
=> chore: remove schedule disclaimer

src/components/BodyText.astro, src/components/practical/PracticalPage.astro, src/pages/news/[slug].astro
Closes: https://github.com/gathering/tgno-frontend/issues/180
=> feat(news,practical): add support for floating images

src/components/competitions/SportsBox.astro, src/pages/competitions/esport.astro
Closes: https://github.com/gathering/tgno-frontend/issues/195
The new design and functionality parts
=> feat(esport): add tcf competition info

src/components/collapsible/Collapsible.astro, src/components/collapsible/CollapsibleTrigger.astro, src/components/icons/ArrowSymbol.astro, src/components/practical/FaqItem.astro, src/components/practical/PracticalPage.astro, src/pages/practical/[...path].astro
Closes: https://github.com/gathering/tgno-frontend/issues/134
=> feat(faq): make items collapsible to prep for section usage

src/components/floating-nav/FloatingNav.astro, src/components/schedule/Event.astro, src/components/schedule/Schedule.astro, src/pages/schedule/index.astro, src/utils/components.ts
Closes: https://github.com/gathering/tgno-frontend/issues/164
=> feat(schedule): add live schedule indicators and scroll to

src/components/schedule/DisplayEvent.astro, src/pages/display/schedule/index.astro
We had an issue when time was 23:xx and added 2h to it 😅 
Iz fixed now
=> fix: time/date error on display/schedule

src/components/Main.astro, src/components/icons/CalendardSymbol.astro, src/components/icons/ClockSymbol.astro, src/components/icons/LiveSymbol.astro, src/components/schedule/DisplayEvent.astro, src/components/schedule/Event.astro, src/pages/display/schedule/index.astro
=> feat(schedule): big screen adjustments
